@Chrona.Time_HostAddress = http://localhost:5000/api

GET {{Chrona.Time_HostAddress}}/employees
Accept: application/json
###
PUT {{Chrona.Time_HostAddress}}/employees
Accept: application/json

{
	id: 1,
	name: "NewName"
}
###
